### ISSUE TITLE
Hand of God Forge is broken

### ISSUE THREAD

**Issue by danzargar** [BeatnikStation/BeatnikStation#18]
You can't put metal and stuff in it

**Comment by GeneralGoose** [comment]
works for me

**Comment by danzargar** [comment]
Hmm i think it is a issue with my pc compileing the code wrong i redownloaded the code and i am going to test it again

**Comment by danzargar** [comment]
Nevermind i tested more on my own and it worked fine must have been Borked code on my end sorry for wasteing time
